spring:
  application:
    name: HotelBooking
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 8081
management:
  endpoints:
    jmx:
      exposure:
        include: '*'